-- MySQL Script generated by MySQL Workbench
-- 10/20/15 17:37:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `hash` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`currency` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `amount` FLOAT NULL DEFAULT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `currency_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`, `currency_id`)  COMMENT '',
  INDEX `fk_account_user_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_account_currency1_idx` (`currency_id` ASC)  COMMENT '',
  CONSTRAINT `fk_account_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bank`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `bank`.`currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `price` FLOAT NULL DEFAULT NULL COMMENT '',
  `incoming_user_id` INT NOT NULL COMMENT '',
  `outgoing_user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `incoming_user_id`, `outgoing_user_id`)  COMMENT '',
  INDEX `fk_transaction_user1_idx` (`incoming_user_id` ASC)  COMMENT '',
  INDEX `fk_transaction_user2_idx` (`outgoing_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`incoming_user_id`)
    REFERENCES `bank`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_user2`
    FOREIGN KEY (`outgoing_user_id`)
    REFERENCES `bank`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
